name: linux

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [debug, release]

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-linux-${{ matrix.build_type }}
      cancel-in-progress: true

    steps:
      - name: Setup llvm
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20 all

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # WyriHaximus/github-action-get-previous-tag@master need it
          fetch-depth: 0

      - name: Package
        run: |
          xmake config --yes --verbose --plat=linux --arch=x86_64 --toolchain=clang-20 --mode=${{ matrix.build_type }}

      - name: Get Previous tag
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/package/x86_64-linux-gnu-${{ matrix.build_type }}.tar.xz
          asset_name: build/package/x86_64-linux-gnu-${{ matrix.build_type }}.tar.xz
          tag: ${{ steps.previous_tag.outputs.tag }}
          overwrite: true
