name: windows

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - build_type: release
            runtimes: MD
            lto: "n"
          - build_type: release
            runtimes: MT
            lto: "y"

    steps:
      - name: Setup llvm
        uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          buckets: main
          apps: llvm

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: '.xmake-cache'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package
        run: |
          xmake config --yes --verbose --runtimes=${{ matrix.runtimes }} --policies=build.optimization.lto:${{ matrix.lto }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build/package/*
          path: artifacts/windows/
